# These are supported funding model platforms

github: ChamodKeshan
patreon: ChamodKeshan
open_collective: ChamodKeshan # Replace with a single Open Collective username
ko_fi: ChamodKeshan # Replace with a single Ko-fi username
tidelift: ChamodKeshan # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: ChamodKeshan # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: ChamodKeshan # Replace with a single Liberapay username
issuehunt: ChamodKeshan # Replace with a single IssueHunt username
otechie: ChamodKeshan # Replace with a single Otechie username
custom: ChamodKeshan # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
